import time
from selenium import webdriver
chromeOptions = webdriver.ChromeOptions()
chromeOptions.add_experimental_option('useAutomationExtension', False)
chromeOptions.add_experimental_option("prefs",{"download.default_directory" : "D:\Bin"})
driver=webdriver.Chrome(executable_path="D:\Software\Selenium_Python\chromedriver_win32\chromedriver.exe", desired_capabilities = chromeOptions.to_capabilities())
driver.implicitly_wait(5)
driver.get("http://demo.automationtesting.in/FileDownload.html")
driver.maximize_window()
time.sleep(2)
driver.find_element_by_id("textbox").send_keys("testng download text file")
time.sleep(2)
driver.find_element_by_id("createTxt").click()
time.sleep(2)
driver.find_element_by_id("link-to-download").click()
time.sleep(2)
driver.find_element_by_id("pdfbox").send_keys("testng download pdf file")
time.sleep(2)
driver.find_element_by_id("createPdf").click()
time.sleep(2)
driver.find_element_by_id("pdf-link-to-download").click()
time.sleep(2)
driver.quit()
