import time
from selenium import webdriver
from selenium.webdriver import ActionChains
from selenium.webdriver.common import keys
chromeOptions = webdriver.ChromeOptions()
chromeOptions.add_experimental_option('useAutomationExtension', False)
driver=webdriver.Chrome(executable_path="D:\Software\Selenium_Python\chromedriver_win32\chromedriver.exe", desired_capabilities = chromeOptions.to_capabilities())
driver.maximize_window()
driver.implicitly_wait(5)
driver.get("http://www.edureka.co/")
driver.maximize_window()
time.sleep(2)
builder = ActionChains(driver)
time.sleep(2)
builder.move_to_element(driver.find_element_by_id("header_topcat")).perform()
time.sleep(2)
link = driver.find_element_by_css_selector("#software-testing-certification-courses")
time.sleep(2)
builder.move_to_element(link).perform()
time.sleep(2)
driver.find_element_by_xpath("//ul[@class='dropdown-menu']//li//a[text()='Software Testing']").click()
time.sleep(2)
act = driver.find_element_by_id("search-inp")
time.sleep(2)
builder.move_to_element(act).click().perform()
time.sleep(2)
act.send_keys("Selenium")
time.sleep(2)
search = driver.find_element_by_xpath("//span[@class='typeahead__button']")
time.sleep(2)
#search.click()
builder.move_to_element(search).click().perform()
#builder.click(act)
time.sleep(2)
#builder.key_down(search,keys.Keys.SHIFT)
time.sleep(2)
#builder.send_keys(act,"Selenium")
#time.sleep(2)
#builder.key_up(search,keys.Keys.SHIFT)
time.sleep(2)
#builder.click(search)
time.sleep(2)
#builder.perform()
time.sleep(2)
driver.quit()