import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
chromeOptions = webdriver.ChromeOptions()
chromeOptions.add_experimental_option('useAutomationExtension', False)
driver=webdriver.Chrome(executable_path="D:\Software\Selenium_Python\chromedriver_win32\chromedriver.exe", desired_capabilities = chromeOptions.to_capabilities())
driver.implicitly_wait(5)
driver.get("https://fs2.formsite.com/meherpavan/form2/")
driver.maximize_window()
time.sleep(2)
maleRadioButton = driver.find_element(By.ID,"RESULT_RadioButton-8_0").is_selected()
femaleRadioButton = driver.find_element(By.ID,"RESULT_RadioButton-8_1").is_selected()
print(maleRadioButton)
print(femaleRadioButton)
time.sleep(2)
male = driver.find_element(By.ID,"RESULT_RadioButton-8_0")
action = ActionChains(driver)
action.move_to_element(male).click(male).perform()
#driver.find_element(By.ID,"RESULT_RadioButton-8_0").click()
#driver.find_element_by_id("RESULT_RadioButton-8_0").click()
#driver.find_element_by_xpath("//input[@value='Radio-0']").click
#driver.find_element_by_css_selector("input#RESULT_RadioButton-8_0").click()
#time.sleep(2)
#driver.find_element(By.ID,"RESULT_RadioButton-8_1").click()
maleRadioButton1 = driver.find_element(By.ID,"RESULT_RadioButton-8_0").is_selected()
femaleRadioButton1 = driver.find_element(By.ID,"RESULT_RadioButton-8_1").is_selected()
print(maleRadioButton1)
print(femaleRadioButton1)
driver.find_element_by_id("RESULT_CheckBox-9_0").is_selected()
sunday = driver.find_element_by_id("RESULT_CheckBox-9_0")
action.move_to_element(sunday).click(sunday).perform()
time.sleep(2)
driver.quit()
