import time
from selenium import webdriver
from selenium.webdriver import ActionChains
from datetime import datetime
currentDateTime = datetime.now()
print(" Current date & time now :"+str(currentDateTime))
dt_string = currentDateTime.strftime("%d/%m/%Y %H:%M:%S")
print("date and time =", dt_string)
chromeOptions = webdriver.ChromeOptions()
chromeOptions.add_experimental_option('useAutomationExtension', False)
driver=webdriver.Chrome(executable_path="D:\Software\Selenium_Python\chromedriver_win32\chromedriver.exe", desired_capabilities = chromeOptions.to_capabilities())
driver.implicitly_wait(5)
driver.get("https://192.168.152.101/tsc/client/home/")
driver.maximize_window()
time.sleep(2)
driver.find_element_by_xpath("//*[@id='loginform']/div[2]/div[2]/div[2]").click()
languageCount = driver.find_elements_by_xpath("//body/div[3]/div[2]/div/div/div/div")
print(len(languageCount))
time.sleep(2)
for language in languageCount:
    print(language.text)
    if language.text == "English":
       language.click()
time.sleep(2)
driver.find_element_by_id("UsernameInput").send_keys("Admin")
time.sleep(2)
driver.find_element_by_id("password").send_keys("")
time.sleep(2)
driver.find_element_by_id("SubmitButton").click()
time.sleep(2)
driver.find_element_by_id("Admin").click()
time.sleep(2)
driver.find_element_by_id("Admin.Signs").click()
time.sleep(2)
driver.find_element_by_id("Admin.Signs.Layout").click()
time.sleep(2)
driver.find_element_by_id("VerticalBox2.ButtonNew").click()
time.sleep(2)
driver.find_element_by_id("HorizontalBoxName.TextName").send_keys("Automatically Created Layout : "+str(dt_string))
time.sleep(2)
driver.find_element_by_id("HorizontalBoxSelection.HorizontalBoxCategory.ComboBoxCategory").click()
time.sleep(2)
#categoryCount = driver.find_elements_by_xpath("//body/div[3]/div[4]/div/div/div/div[2]/div")
categoryCount = driver.find_elements_by_class_name("qx-listbox-listitem")
time.sleep(2)
for category in categoryCount:
    print(category.text)
    if category.text == "codixx":
       category.click()
time.sleep(2)
driver.find_element_by_id("PanelDisplayElement.PanelDisplayElement.PanelLayoutElements.VerticalBoxLayoutElements.HorizontalBoxButtons.ButtonAdd").click()
time.sleep(2)
driver.find_element_by_id("PanelLayoutElement.VerticalBoxLayoutElement.HorizontalBoxName.TextName").send_keys("Automatically Created Element : "+str(dt_string))
time.sleep(2)
driver.find_element_by_id("PanelLayoutElement.VerticalBoxLayoutElement.HorizontalBoxKind.ComboBoxKind").click()
time.sleep(4)
#elementCount = driver.find_elements_by_xpath("//body/div[3]/div[5]/div/div/div/div[2]/div")
elementCount = driver.find_elements_by_class_name("qx-listbox-listitem")

for element in elementCount:
    print(element.text)
    if element.text == "Text":
        element.click()
time.sleep(2)
driver.find_element_by_id("HorizontalBoxButtons.ButtonOK").click()
time.sleep(2)
driver.find_element_by_xpath("//div[@id='PanelDisplayElement.PanelDisplayElement.PanelLayoutElements.VerticalBoxProperties.TableProperties']/div/div/div[1]/div/div[2]/div/div/div[1]").click()
#action = ActionChains(driver)
#action.key_down().perform()
#time.sleep(1)
#action.key_down().perform()
#time.sleep(1)
#action.key_down().perform()
#time.sleep(1)
#action.key_down().perform()
#time.sleep(1)
#action.key_down().perform()
#time.sleep(1)
#action.key_down().perform()
time.sleep(2)
driver.find_element_by_id("HorizontalBoxButtons.ButtonSave").click()
time.sleep(2)
driver.quit()